server:
  port: 8085

spring:
  application:
    name: notification-service
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: ${MAIL_HOST:smtp.mailtrap.io}
    port: ${MAIL_PORT:2525}
    username: ${MAIL_USERNAME:test}
    password: ${MAIL_PASSWORD:test}

management:
  endpoints:
    web:
      exposure:
        include: health,info

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    redis:
      host: redis
