server:
  port: 8082

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/clothing_store?currentSchema=product_schema
    username: admin
    password: dev_password_123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        default_schema: product_schema
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 600000

management:
  endpoints:
    web:
      exposure:
        include: health,info

cloudinary:
  url: ${CLOUDINARY_URL:}

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/clothing_store?currentSchema=product_schema
  data:
    redis:
      host: redis
